import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import Image from "next/image";
import Profile from "../../public/profile.jpg";
import { Projects } from "../const/project";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Sital Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-36 dark:bg-gray-900">
        <section className=" min-h-screen ">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons dark:text-gray-300">
              Developed By Sital
            </h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => {
                    setDarkMode(!darkMode);
                  }}
                  className="cursor-pointer dark:text-slate-300 mx-10"
                />
              </li>
              <li>
                <Link href="/resume">
                  <button className="bg-gradient-to-r from-cyan-500 to-cyan-900 text-white px-4 py-2 rounded-md ml-8">
                    Resume
                  </button>
                </Link>
              </li>
            </ul>
          </nav>
          <SocialMediaLogo />
        </section>
        {/* Next Section cards*/}
        <section className="mt-5">
          <div className="flex justify-center flex-col items-center">
            <h3 className="text-3xl py-2 font-bold dark:text-gray-300">
              Portfolio
            </h3>

            <p className="text-md text-gray-500 py-2 leading-8 dark:text-gray-400">
              I have done many college projects and other projects that are
              shown below.
            </p>
          </div>

          {/* cards */}
          <div className="flex gap-14 flex-wrap py-4 justify-center">
            {Projects.map((project, index) => {
              return <Card project={project} key={index} />;
            })}
          </div>
        </section>
      </main>
    </div>
  );
}

const SocialMediaLogo = () => {
  return (
    <>
      <div className="text-center p-10 ">
        <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl ">
          Sital Nagarkoti
        </h2>
        <h3 className="text-2xl py-2 md:text-3xl dark:text-gray-300">
          Developer and Designer
        </h3>
        <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-gray-400">
          Computer Engineering Student graduated from Pulchowk Campus.
          Interested in Web Development and Mobile Development. Would love to do
          projects related on web development.
        </p>
      </div>
      <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
        <a href="https://twitter.com/NagarkotiShital" className="">
          <AiFillTwitterCircle />
        </a>
        <a
          href="https://www.linkedin.com/in/sital-nagarkoti-b62409241/"
          className=""
        >
          <AiFillLinkedin />
        </a>
        <a href="https://github.com/Sital999" className="">
          <AiFillGithub />
        </a>
      </div>
      <div className="relative overflow-hidden mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 md:h-96 md:w-96">
        <Image src={Profile} layout="fill" objectFit="cover" alt="profile" />
      </div>
    </>
  );
};

const Card = ({ project }) => {
  const [isCardClicked, setIsCardClicked] = useState(false);

  return (
    <div
      onClick={() => setIsCardClicked(!isCardClicked)}
      className={`transform ease-in-out duration-500 hover:scale-105 rounded-lg px-5 py-4 leading-normal bg-cardColor shadow-md shadow-slate-300 w-72 h-96 dark:text-white dark:shadow-sm dark:shadow-white dark:bg-sky-900 dark:opacity-80`}
    >
      {isCardClicked ? (
        <div className="flex flex-col gap-6">
          <h1 className="font-bold text-lg">{project.title}</h1>
          <h2>{project.description}</h2>
          <div className="flex gap-4 flex-wrap">
            {project.tools.map((tool, index) => {
              return (
                <div
                  key={index}
                  className=" rounded shadow shadow-slate-400 px-5 py-2 bg-slate-600 text-white dark:bg-slate-50 dark:text-black"
                >
                  {tool}
                </div>
              );
            })}
          </div>
        </div>
      ) : (
        <div className="flex flex-col gap-4">
          <h1 className="font-bold text-lg">{project.title}</h1>
          <Image src={project.img} alt={project.img} />
        </div>
      )}
    </div>
  );
};
