import { cn } from "@lib/utils";
import { Provider } from "jotai";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../assets/css/globals.css";

const inter = Inter({ subsets: ["latin"] });
``;

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated By ...",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(" overflow-x-hidden bg-stone-200", inter.className)}>
        <Provider>
          <div>{children}</div>
        </Provider>
      </body>
    </html>
  );
}
