import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../assets/css/globals.css";
import { cn } from "../lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated By ...",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "max-h-screen w-screen overflow-x-hidden bg-stone-200",
          inter.className
        )}
      >
        <div className="h-screen w-screen">{children}</div>
      </body>
    </html>
  );
}
