import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import Image from "next/image";
import deved from "../public/dev-ed-wave.png";
import letter from "../public/letter.png";
import mobile from "../public/mobile.png";
import project from "../public/project.png";
import war from "../public/war.png";

// import web1 from "../public/web1.png";
// import web2 from "../public/web2.png";
// import web3 from "../public/web3.png";
// import web4 from "../public/web4.png";
// import web5 from "../public/web5.png";
// import web6 from "../public/web6.png";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Sital Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className=" min-h-screen ">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons dark:text-gray-300">
              Developed By Sital
            </h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => {
                    setDarkMode(!darkMode);
                  }}
                  className="cursor-pointer dark:text-slate-300 mx-10"
                />
              </li>
              <li>
                <Link href="/resume/resume">
                  <button className="bg-gradient-to-r from-cyan-500 to-cyan-900 text-white px-4 py-2 rounded-md ml-8">
                    Resume
                  </button>
                </Link>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 ">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl ">
              Sital Nagarkoti
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-gray-300">
              Developer and Designer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-gray-400">
              Computer Engineering Student currently studying at Pulchowk
              Campus. Interested in Web Development and Mobile Development.
              Would love to do projects related on web development.
            </p>
          </div>

          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <a href="https://twitter.com/NagarkotiShital" className="">
              <AiFillTwitterCircle />
            </a>
            <a
              href="https://www.linkedin.com/in/sital-nagarkoti-b62409241/"
              className=""
            >
              <AiFillLinkedin />
            </a>
            <a href="https://github.com/Sital999" className="">
              <AiFillGithub />
            </a>
          </div>
          <div className="relative overflow-hidden mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 md:h-96 md:w-96">
            <Image src={deved} layout="fill" objectFit="cover" />
          </div>
        </section>
        {/* Next Section cards*/}
        <section className="mt-5">
          <div>
            <h3 className="text-3xl py-2 dark:text-gray-300">Portfolio</h3>

            <p className="text-md text-gray-500 py-2 leading-8 dark:text-gray-400">
              I have done many college projects and other projects that are
              shown below.
            </p>
          </div>

          {/* cards */}
          <div className="lg:flex gap-10 ">
            <div className="text-center shadow-2xl p-10 rounded-xl my-10 dark:bg-slate-300 basis-1/2 flex-1">
              <a href="https://github.com/Sital999/Letter-Recommendation">
                <h3 className="text-xl font-medium  pb-8 text-blue-800">
                  Recommendation Letter
                </h3>
              </a>
              <Image src={letter} width={100} height={100} />
              <p className="py-2">
                A web application that helps student and teacher to generate a
                recommendation letter for Bachelors and Masters.
              </p>
              <div className="text-cyan-500 pt-10 text-sm gap-4 flex">
                <button className="bg-cyan-900 rounded-xl p-2 text-gray-50">
                  Django
                </button>
                <button className="bg-cyan-900 rounded-xl p-2 text-gray-50">
                  JS
                </button>
                <button className="bg-cyan-900 rounded-xl p-2 text-gray-50">
                  SQL
                </button>
              </div>
            </div>
            <div className="text-center shadow-2xl p-10 rounded-xl my-10 dark:bg-slate-300 basis-1/2 flex-1">
              <a href="https://github.com/Sital999/ioe_app">
                <h3 className="text-xl font-medium pb-8 text-blue-800">
                  IOE Mobile Application
                </h3>
              </a>
              <Image src={mobile} width={100} height={100} />
              <p className="py-2">
                A mobile application for students of IOE with multiple features
                like attendance, routine , result.
              </p>
              <div className="text-cyan-500 pt-10 text-sm gap-4 flex">
                <button className="bg-cyan-900 rounded-xl p-2 text-gray-50">
                  Rest
                </button>
                <button className="bg-cyan-900 rounded-xl p-2 text-gray-50">
                  Flutter
                </button>

                <button className="bg-cyan-900 rounded-xl p-2 text-gray-50">
                  SQL
                </button>
              </div>
            </div>
            <div className="text-center shadow-2xl p-10 rounded-xl my-10 dark:bg-slate-300 basis-1/2 flex-1">
              <a href="https://github.com/Sital999/react_project">
                <h3 className="text-xl font-medium pb-8 text-blue-800">
                  React Projects
                </h3>
              </a>
              <Image src={project} width={100} height={100} />
              <p className="py-2">
                A couple of personal projects while learning React. These
                Projects are interesting and nice so visit once.
              </p>
              <div className="text-cyan-500 pt-10 text-sm gap-4 flex">
                <button className="bg-cyan-900 rounded-xl p-2 text-gray-50">
                  React
                </button>
                <button className="bg-cyan-900 rounded-xl p-2 text-gray-50">
                  Material UI
                </button>
              </div>
            </div>
            <div className="text-center shadow-2xl p-10 rounded-xl my-10 dark:bg-slate-300 basis-1/2 flex-1">
              <a href="https://github.com/Sital999/Cpp-Programming-WW3t">
                <h3 className="text-xl font-medium pb-8 text-blue-800">
                  World War II
                </h3>
              </a>
              <Image src={war} width={100} height={100} />
              <p className="py-2">
                World War game made for fun. It is a dual player mode where they
                shoot each and terminates other and win the game.
              </p>
              <div className="text-cyan-500 pt-10 text-sm gap-4 flex">
                <button className="bg-cyan-900 rounded-xl p-2 text-gray-50">
                  C++
                </button>
                <button className="bg-cyan-900 rounded-xl p-2 text-gray-50">
                  SFML
                </button>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
